### ISSUE TITLE
Issues with Neural(Meta)Group

### ISSUE THREAD

**Issue by Silmathoron** [tfardet/NNGT#142]
In NNGT 2.2, default ``NeuralGroup`` should be excitatory.
There is also an issue with ``MetaGroup`` name attribute (e.g. using ``create_metagroup`` function).

**Comment by tfardet** [comment]
NeuralGroup default fixed by 1a95fe3843c3c33d8e62bb92bacb76b13fd27adc, could not reproduce the metagroup issue
